service: include('AgentSupportServiceConfig')
---
AgentSupportServiceConfig:
    appName: str()
    firebase: include('FirebaseConfig')
---
FirebaseConfig:
  project: str()
  database: str()
  collection: str()
