version: 1
disable_existing_loggers: False
formatters:
  uvicorn:
    (): uvicorn.logging.DefaultFormatter
    fmt: "%(levelprefix)s %(asctime)s - %(name)s - %(message)s"
    use_colors: true
handlers:
  console:
    class: logging.StreamHandler
    formatter: uvicorn
    stream: ext://sys.stdout
loggers:
  uvicorn:
    handlers: [console]
    level: INFO
root:
  level: INFO
  handlers: [console]
